#ifndef _CATACOMB_TILES_H_
#define _CATACOMB_TILES_H_

#define TILE_TYPE_SPAWN 230

#define TILE_TYPE_TELE  231
#define MAX_TELE_ANIMATIONS 4
#define TELE_ANIMATION_SIZE 32

#define TILE_PINK_BACKGROUND 129<<3

#endif // _CATACOMB_TILES_H_
